      {w:"validate",p:"v.",d:"校验；验证数据/配置合法性",e:"Validate the input before the injection happens. You know what happened last time."},
      {w:"worker",p:"n.",d:"工作进程；后台任务执行单元",e:"The worker pool is exhausted. 20 requests queued, 4 threads alive."},
      {w:"access",p:"n./v.",d:"访问；读写权限",e:"Access denied. The permissions on that file are 000. Not a typo."},
      {w:"bandwidth",p:"n.",d:"带宽；网络最大传输速率",e:"Bandwidth throttled: the family next door is streaming 4K on your WiFi."},
      {w:"cache",p:"n./v.",d:"缓存；临时存储加速",e:"Cache invalidation is one of the two hard problems in computer science."},
      {w:"cluster",p:"n.",d:"集群；多台协同工作的服务器",e:"The cluster auto-scaled from 3 to 20 nodes in 90 seconds. Config was spot on."},
      {w:"debug",p:"v./n.",d:"调试；定位并修复代码缺陷",e:"Debugging is like being the detective in a crime movie where you're also the murderer."},
      {w:"endpoint",p:"n.",d:"端点；API的URL路径",e:"The health endpoint returned 200 but the database was on fire. Classic."},
      {w:"fork",p:"v./n.",d:"派生；创建进程/仓库副本",e:"Fork the repo before you break the main branch. Your local experiments await."},
      {w:"garbage",p:"n.",d:"垃圾；无用的内存/数据",e:"Garbage collection kicked in and the app froze for 400ms. Java things."},
      {w:"hash",p:"n./v.",d:"哈希；数据映射为固定长度摘要",e:"The hash of the downloaded file didn't match. You downloaded a corrupted binary."},
      {w:"idle",p:"adj./v.",d:"空闲的；无活动状态",e:"The idle connection timed out after 300 seconds of silence."},
      {w:"job",p:"n.",d:"任务；定时执行的批处理",e:"The cron job ran twice. The duplicate entries in the DB say hi."},
      {w:"key",p:"n.",d:"密钥；API鉴权凭证",e:"Someone committed the API key to GitHub. Rotate it. Now."},
      {w:"log",p:"n./v.",d:"日志；系统记录的信息",e:"The logs are verbose. Filter by ERROR to find what you actually care about."},
      {w:"memory",p:"n.",d:"内存；RAM存储空间",e:"Memory leak detected: the process grew to 8GB and the OOM killer woke up."},
      {w:"namespace",p:"n.",d:"命名空间；资源隔离域",e:"The Kubernetes namespace dev-team: where all rules are broken first."},
      {w:"offset",p:"n./v.",d:"偏移量；分页起始位置",e:"The pagination offset is 1000. Your query will timeout. Trust me."},
      {w:"ping",p:"n./v.",d:"网络连通性测试",e:"Ping 8.8.8.8—the universal sysadmin prayer gesture."},
      {w:"queue",p:"n./v.",d:"队列；等待处理的任务列表",e:"The job queue depth hit 10K. The worker pool couldn't keep up."},
      {w:"replica",p:"n.",d:"副本；数据的冗余拷贝",e:"Three replicas of the database: one writer, two readers, zero drama."},
      {w:"script",p:"n./v.",d:"脚本；自动化执行的程序序列",e:"The deployment script had a typo on line 3. The entire cluster went down."},
      {w:"token",p:"n.",d:"令牌；身份验证凭据",e:"The JWT token expired. Every single user got logged out simultaneously."},
      {w:"upload",p:"v./n.",d:"上传；文件从本地到服务器",e:"The 4GB upload failed at 99%. Compress next time."},
      {w:"volume",p:"n.",d:"卷；持久化存储空间",e:"The Docker volume mounted successfully. The data survived the container restart."},
      {w:"watchdog",p:"n.",d:"看门狗；监督进程健康的机制",e:"The watchdog timer expired. The system rebooted without asking permission."},
      {w:"bit",p:"n.",d:"比特；最基本的二进制单位",e:"A bit flipped in the wrong place. The entire checksum chain collapsed."},
      {w:"checksum",p:"n.",d:"校验和；数据完整性验证",e:"The checksum mismatch on line 347. Packet loss somewhere in the chain."},
      {w:"directory",p:"n.",d:"目录；文件系统的文件夹",e:"The root directory is 95% full. The culprit: systemd journal logs."},
      {w:"environment",p:"n.",d:"环境；运行上下文",e:"The production environment doesn't have debug mode for a reason."},
      {w:"failover",p:"n.",d:"故障切换；主备系统自动切换",e:"The failover completed in 3 seconds. Nobody noticed the primary died."},
      {w:"healthcheck",p:"n.",d:"健康检查；服务存活状态验证",e:"The healthcheck endpoint kept returning 503. The orchestrator got impatient."},
      {w:"instance",p:"n.",d:"实例；云服务器/进程副本",e:"The EC2 instance type was t2.micro. You got what you paid for."},
      {w:"journal",p:"n.",d:"日志；systemd的日志系统",e:"The journal grew to 4GB. Nobody rotated it. Nobody ever does."},
      {w:"kill",p:"v./n.",d:"终止（进程）",e:"SIGKILL cannot be caught. The process didn't even know what hit it."},
      {w:"localhost",p:"n.",d:"本机地址；127.0.0.1",e:"localhost: the only address that never lies and never scales."},
      {w:"master",p:"n.",d:"主节点/主分支；权威版本",e:"The master branch is protected. The rebase still went wrong."},
      {w:"notify",p:"v.",d:"通知；告警推送",e:"The monitoring system notified you 3 hours ago. You just now checked."},
      {w:"optimize",p:"v.",d:"优化；提升系统性能",e:"Optimizing the query from 12 seconds to 1.2 seconds. That's a win."},
      {w:"priority",p:"n.",d:"优先级；任务紧急程度",e:"Priority 1 incident: everywhere is on fire. Priority 2: just the database."},
      {w:"recovery",p:"n.",d:"恢复；从故障状态复原",e:"The recovery took 47 minutes. The RTO was 30. You owe an explanation."},
      {w:"scheduler",p:"n.",d:"调度器；任务时间表管理器",e:"The cron scheduler ran the job at 03:00. The server was down at 03:01."},
      {w:"storage",p:"n.",d:"存储；硬盘/对象存储",e:"The storage array lost two disks. The RAID rebuilt from parity. You got lucky."},
      {w:"timeout",p:"n./v.",d:"超时；等待时间耗尽",e:"The connection timed out after 30 seconds. The server is not coming back."},
      {w:"upstream",p:"n./adj.",d:"上游；源站服务器",e:"The upstream server returned 502. The proxy doesn't know what to do either."},
      {w:"virtual",p:"adj.",d:"虚拟的；虚存/虚拟机",e:"The virtual machine runs atop a hypervisor that runs atop a host that runs atop hope."},
      {w:"workflow",p:"n.",d:"工作流；CI/CD流水线",e:"The CI workflow failed at linting. The developer's ego is now involved."},
      {w:"yield",p:"v./n.",d:"产生/让出；进程主动释放CPU",e:"The generator yields control to the event loop—cooperative multitasking at its finest."},
      {w:"zone",p:"n.",d:"区域；DNS/防火墙域",e:"The DNS zone transfer failed. The entire domain is now pointing to nowhere."}
    ]
  },
  mystic: {
    name:'神秘学 · 命理', icon:'🔮', theme:'mys', progressClass:'mys-progress',
    desc:'奥义、占卜、星辰——通晓命运的语言',
    words:[
      {w:"arcana",p:"n.",d:"奥秘，奥义；塔罗牌的阿卡纳",e:"The Fool is card zero—not ignorance, but the courage to step into the unknown."},
      {w:"oracle",p:"n.",d:"神谕；传递神圣信息的媒介",e:"The oracle spoke in riddles. It always does. The answers are yours to unwrap."},
      {w:"omen",p:"n.",d:"预兆，征兆",e:"A crow on the window sill at midnight—whether good omen or bad depends on who's asking."},
      {w:"divine",p:"adj./v.",d:"神圣的；占卜，预测",e:"To divine the future is to read the patterns the universe left behind."},
      {w:"trance",p:"n.",d:"出神状态；恍惚，入定",e:"The medium slipped into a trance, her eyes rolling back before the words came."},
      {w:"vortex",p:"n.",d:"漩涡；能量的旋流中心",e:"The vortex of energy swirled above the altar—a tear in the fabric of the mundane."},
      {w:"pendulum",p:"n.",d:"摆锤；占卜用的垂摆",e:"The pendulum swings north-south for yes. East-west for no. Still means ask again."},
      {w:"zodiac",p:"n.",d:"黄道十二宫；星座系统",e:"Your zodiac sign is just the start. The real story is in the houses and aspects."},
      {w:"eclipse",p:"n.",d:"日月食；遮蔽天光的天象",e:"An eclipse is the universe reminding you: even light has its gaps."},
      {w:"altar",p:"n.",d:"祭坛，供台",e:"The altar held a black candle, a quartz crystal, and a feather that smelled of rain."},
      {w:"sigil",p:"n.",d:"印记，符文；带有特定意图的符号",e:"He carved the sigil into the wooden floor—a lock, a key, and a promise."},
      {w:"lunar",p:"adj.",d:"月亮的；与月相相关的",e:"Lunar phases guide the timing of rituals. New moon for beginnings, full for release."},
      {w:"astral",p:"adj.",d:"星辰的；星体层面的",e:"Astral projection: when your soul takes a walk without asking your body's permission."},
      {w:"celestial",p:"adj.",d:"天体的；天空的",e:"The celestial bodies don't cause events—they're clocks that tell you when."},
      {w:"crystal",p:"n./adj.",d:"水晶；具有能量属性的矿物",e:"Clear quartz amplifies intention. Amethyst protects. Obsidian cuts through lies."},
      {w:"destiny",p:"n.",d:"天命，宿命",e:"Destiny is not a path laid out. It's a crossroads you keep coming back to."},
      {w:"elemental",p:"adj./n.",d:"元素的；自然精灵",e:"Four elements, four directions, four gates. The fifth is always the self."},
      {w:"fate",p:"n.",d:"命运；不可改变的轨迹",e:"Fate is what happens when you stop fighting the current. Not surrender—alignment."},
      {w:"grimoire",p:"n.",d:"魔法书；记载咒文的典籍",e:"The grimoire was bound in leather that had never come from a cow."},
      {w:"hermit",p:"n.",d:"隐士；塔罗牌的隐士牌",e:"The Hermit carries a lantern not to see the path, but to light it for others."},
      {w:"incense",p:"n.",d:"熏香；仪式中焚烧的香料",e:"The incense burned with a fragrance that smelled like afternoon and memory."},
      {w:"karma",p:"n.",d:"业力；因果循环的法则",e:"Karma isn't punishment. It's the universe's way of balancing its books."},
      {w:"mantra",p:"n.",d:"咒语；反复念诵的真言",e:"The mantra repeated until the words lost meaning—and then, the real meaning surfaced."},
      {w:"necromancy",p:"n.",d:"死灵术；与亡者沟通的技艺",e:"Necromancy is just ancestry research with a darker dress code."},
      {w:"occult",p:"adj./n.",d:"奥秘的；隐秘的知识/实践",e:"The occult isn't hidden because it's forbidden. It's hidden because most aren't ready."},
      {w:"pentacle",p:"n.",d:"五芒星；土元素的象征符号",e:"The pentacle drawn on the floor was more map than protection."},
      {w:"runes",p:"n.",d:"如尼文；北欧的占卜符号系统",e:"The runes were cast: Ansuz for communication, Hagalaz for disruption. The answer was clear."},
      {w:"seance",p:"n.",d:"降灵会；与灵魂沟通的集会",e:"The séance table lifted an inch off the floor. Everyone pretended not to notice."},
      {w:"talisman",p:"n.",d:"护身符；具有防护力量的物品",e:"The talisman was warm against his chest—a small comfort against a large darkness."},
      {w:"augury",p:"n.",d:"卜兆；通过鸟类的飞行占卜",e:"Augury read the flight patterns of birds. The answer was always in the direction."},
      {w:"chakra",p:"n.",d:"脉轮；身体中的能量中心",e:"Root chakra blocked: the feeling of being unmoored. Crown open: the universe rushes in."},
      {w:"divination",p:"n.",d:"占卜；预见未来的实践总称",e:"Divination is less about predicting the future and more about listening to the present."},
      {w:"enigma",p:"n.",d:"谜；无法解释的存在",e:"The universe is an enigma that doesn't want to be solved—it wants to be witnessed."},
      {w:"familiar",p:"n./adj.",d:"女巫的灵兽；熟悉的",e:"The cat wasn't her familiar. The cat was something older that tolerated being called a cat."},
      {w:"glyph",p:"n.",d:"（神秘的）符号，雕刻字符",e:"The glyphs glowed in sequence, spelling out a warning in a language older than speech."},
      {w:"hex",p:"n./v.",d:"恶咒；施加负面魔法",e:"The hex wasn't death—it was inconvenience. A thousand small misfortunes."},
      {w:"invocation",p:"n.",d:"召唤；祈请某方力量的仪式",e:"Invocation is inviting a force into yourself. Evocation is asking it to stand beside you."},
      {w:"lemniscate",p:"n.",d:"∞符号；无限循环的象征",e:"The lemniscate above the Magician's head: infinite possibility, finite execution."},
      {w:"medium",p:"n.",d:"灵媒；沟通阴阳两界的人",e:"The medium spoke in a voice that wasn't hers—and described things she couldn't have known."},
      {w:"numinous",p:"adj.",d:"令人敬畏的神秘感；神圣的",e:"The numinous presence filled the temple—something vast and utterly indifferent."},
      {w:"paranormal",p:"adj.",d:"超自然的；科学无法解释的",e:"Paranormal activity: the polite term for when reality glitches."},
      {w:"quintessence",p:"n.",d:"第五元素；以太；事物精华",e:"Quintessence—the fifth element—is the stuff that connects all the other stuff."},
      {w:"reincarnation",p:"n.",d:"转世；灵魂的再次投胎",e:"Reincarnation isn't a second chance. It's another lesson with a different face."},
      {w:"scry",p:"v.",d:"水晶球透视；凝视以获取幻象",e:"She scried into the obsidian mirror, watching images form in the black depth."},
      {w:"tarot",p:"n.",d:"塔罗牌；78张牌的占卜系统",e:"Tarot doesn't tell you what will happen. It tells you what you already know but won't face."},
      {w:"umbra",p:"n.",d:"阴影区；日食的本影",e:"The umbra of the eclipse passed over the circle—and for three minutes, the world held its breath."},
      {w:"vestige",p:"n.",d:"残留痕迹；过往的遗留",e:"The vestiges of the old religion survived in children's rhymes and holiday traditions."},
      {w:"wand",p:"n.",d:"魔杖；仪式中的意志指向工具",e:"A wand is just a stick until you believe it's not. That belief is all the magic."},
      {w:"waxing",p:"adj.",d:"（月亮）渐盈的；增长的",e:"Waxing moon: time to build, to grow, to start the things you've been putting off."},
      {w:"yantra",p:"n.",d:"坛城；用于冥想的神秘几何图",e:"The yantra was a geometric map of the cosmos—tracing its lines was a form of prayer."}
    ]
  }
};
